### ISSUE TITLE
Cannot read property 'enableAdvertisingTracking' of undefined

### ISSUE THREAD

**Issue by thib92** [leoilab/react-native-analytics-segment-io#67] opened 2018-08-03 14:49 UTC
Hi !

After following all the steps from the `README.md` file, importing the module in JS files makes my app crash in my iPhone Simulator.

I installed the package throw NPM and added the pod dependency to my `Podfile`, ran `pod install` and `react-native link`, but after importing the module in my JS code, the app crashes at startup, showing the following error :
```
Cannot read property 'enableAdvertisingTracking' of undefined
```

Here is my `Analytics.js` file :
```javascript
// eslint-disable-next-line no-unused-vars
import Analytics, { AnalyticsConstants } from 'react-native-analytics-segment-io';
import { SEGMENT_KEY } from '../../environment';

Analytics.setup(SEGMENT_KEY, {
  flushAt: 1,
  enableAdvertisingTracking: true,
});

export default Analytics;
```

Later, this piece of code tracks an event :
```javascript
import Analytics from '../../utils/Analytics';
...
Analytics.track('Finish tutorial');
```

Removing this code or commeting out the `import Analytics, { AnalyticsConstants } from 'react-native-analytics-segment-io';` statement makes the error go away (but of course I can't use Segment).

Would you have any idea on what could be implied here ?

Thanks a lot !

**Comment by thib92** [comment] 2018-08-03 16:16
Please not that I also had this error message :

`undefined is not an object (evaluating 'RNASegmentIO.enableAdvertisingTracking')`

The two seem to switch between one and the other when I clean the Simulator, run it on another device (iPhone SE Simulator, iPhone X Simulator, etc.).

**Comment by skovhus** [comment] 2018-08-21 18:28
Yes. Seems to be a duplicate of #61.

**Closed by skovhus** 2018-08-21 18:28 UTC
